name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 03:00 执行（北京时间 11:00）
  workflow_dispatch:     # 支持手动触发同步

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 我们稍后手动设置认证信息

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/xiaorouji/openwrt-passwall-packages.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into your main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || echo "No changes to merge"

      - name: Push changes back to your fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
